### ISSUE TITLE
Temperature value is not real - negative values in summer times

### ISSUE THREAD

**Issue by proasnet** [liudger/python-bsblan#255]
Hi, thank you for your work. I am using your api in HA about one year. After updates of a BSB Lan, your API is not working. I worte about it here
https://github.com/fredlcore/BSB-LAN/issues/377
Can you see it please?
Thank you

**Comment by liudger** [comment]
Bsblan for Home assistant is only working with version 1.0. So if yo install this release it should work. I am working on a new release. But my time is really scares. So if this is not working downgrading. You could try to setup something with mqqt. In home assistant forum there is a thread about bsblan

**Comment by proasnet** [comment]
I understand the workload. Same with me. Your API worked until BSB LAN version 2.0.88, not in other versions. That's why I downgraded to 2.0.88 and the API works for me again. Please, when you have time, update the old version.
Thank you so much

**Comment by liudger** [comment]
Fix is coming. The current version of python-bsblan should easily support new firmwares.

I first need to release the new version to home-assistant. I also updated the home assistant component/integrations. This was quite some work as the code has changed a lot for newer integrations.

 The next step is to upgrade my bsblan device and see what need to be updated in python-bsblan. This should be a small bump in the library and could be done in sub release. So I am not sure about the time frame

**Comment by proasnet** [comment]
Great. Its very good news. After this updates, I will test it. Thank you.

**Comment by proasnet** [comment]
Hello diutger, is any news in your update? Thank you.

**Comment by liudger** [comment]
The pull request is there but nobody is reviewing it. 
Please review?! 
https://github.com/home-assistant/core/pull/67399
I am thinking of branching it to HACS. So developing and releases are gonna be a bit faster. But not much time at the moment.
